### ISSUE TITLE
No handling of HTTP 525 status of shields.io

### ISSUE THREAD

**Issue by RobinTail** [tlvince/make-coverage-badge#167]
**Describe the bug**

when https://shields.io/ is down the command creates an empty file instead of throwing an error

**To Reproduce**

Ensure shields.io is down and run the command.

```sh
> yarn make-coverage-badge
yarn run v1.22.11
/node_modules/.bin/make-coverage-badge
Wrote coverage badge to: ./coverage/badge.svg
✨  Done in 1.32s.
> cat ./coverage/badge.svg
```

**Expected behaviour**

error output, no writing to file

**Screenshots**

<img width="1040" alt="Screen Shot 2022-07-04 at 17 55 06" src="https://user-images.githubusercontent.com/13189514/177188242-d0dd5493-ccfe-40c5-858e-4ab15b8dbd1b.png">

**Context**

- OS: MacOS, GitHub CI

**Comment by tlvince** [comment]
Closed by #168
